### ISSUE TITLE
Can't send email invitations on production

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#380]
Example of stack trace:
```
Completed 500 Internal Server Error in 34ms (ActiveRecord: 6.4ms) 
Nov 24 13:29:39 ifme app/web.1:  SocketError (getaddrinfo: Servname not supported for ai_socktype): 
Nov 24 13:29:39 ifme app/web.1:    app/controllers/users/invitations_controller.rb:5:in `create' 
Nov 24 13:29:39 ifme app/web.1:    app/controllers/application_controller.rb:27:in `block in with_timezone' 
Nov 24 13:29:39 ifme app/web.1:    app/controllers/application_controller.rb:27:in `with_timezone'
``` 

Not able to reproduce on local. It's looks like it's a DNS related error.

**Comment by julianguyen** [comment]
So I fixed this - there were multiple issues with the config files for SMTP (raised after we migrated over to dotenv)
Commits: https://github.com/julianguyen/ifme/commit/fd0b498bd3f41000d53f78d631bd4179a9a464e2, https://github.com/julianguyen/ifme/commit/489d5a1d01dc72f7d8e95946630cba8f8c962a91
